version: '3'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  
  web:
    depends_on:
      - db
    build: ./wordpress
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: admin@example.com
    dns: 8.8.8.8
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    ports:
      - "${WP_PORT:-80}:80"

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   #container_name: "wp_phpmyadmin"
  #   ports:
  #     - "8000:80"
  #   environment:
  #     PMA_HOSTS: db
  #     PMA_USER: wordpress
  #     PMA_PASSWORD: wordpress

  mail:
    image: juanluisbaptiste/postfix:latest
    env_file:
      - ./postfix/.env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  cli:
    image: wordpress:cli
    volumes_from:
      - web
    depends_on:
      - db
      - web
    command: "--info"
    user: xfs
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
        
networks:
  default:
    name: nginx_net
    external: true

volumes:
  dbvol: